server:
  port: 8080

mysql:
  host: "localhost"
  user: "root"
  password: "67490009"
  name: "dream_workshop"
  port: 3306

mongodb:
  host: "localhost"
  port: 27017
  name: "dream_workshop"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
